### ISSUE TITLE
TempToken::__clone() Usage

### ISSUE THREAD

**Issue by anthonysterling** [mattkirwan/temp-token#3]
Hi Matt.

Are you defining TempToken::__clone() to prevent the cloning of a token? If so, maybe it should be marked as `private` or throw a [LogicException](http://www.php.net/manual/en/class.logicexception.php) ?

Anthony.

**Comment by mattkirwan** [comment]
?

It is private.

**Comment by anthonysterling** [comment]
Oh dear, sorry Matt!
