### ISSUE TITLE
No way to check token?

### ISSUE THREAD

**Issue by tricoos** [mattkirwan/temp-token#4]
I thought that this library was used to generate and later validate the token.
However, it doesn't look like so. In fact I think I could just use this code to get something similar:
`$token = md5(uniqid($userName, true));`

**Comment by mattkirwan** [comment]
Hi tricoos,

You are absolutely correct. In fact all this does under the hood is that md5 above. What this brings though is the ability to have a token and expiry date together but _crucially_ they would be stored in an external store.

Eg: We generate a token and an expiry. We then store them both in say a MySQL table and then when the customer clicks the token link (maybe a forgot password link) it first looks up that token against that user and checks to see if it's expired in the DB.

But yes your point stands it simply generates a random token with the added benefit of been able to access and _store_ an expiry.
